/* File: f2py_vnormmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Tue Sep 19 14:07:31 2017
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *f2py_vnorm_error;
static PyObject *f2py_vnorm_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    char errstring[256];\
    sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
    PyErr_SetString(f2py_vnorm_error,errstring);\
    /*goto capi_fail;*/\
  } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void vnorm(double*,double*,int);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** vnorm ***********************************/
static char doc_f2py_rout_f2py_vnorm_vnorm[] = "\
vnorm(vecs,mods)\n\nWrapper for ``vnorm``.\
\n\nParameters\n----------\n"
"vecs : input rank-2 array('d') with bounds (n,3)\n"
"mods : in/output rank-1 array('d') with bounds (n)";
/* extern void vnorm(double*,double*,int); */
static PyObject *f2py_rout_f2py_vnorm_vnorm(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *vecs = NULL;
  npy_intp vecs_Dims[2] = {-1, -1};
  const int vecs_Rank = 2;
  PyArrayObject *capi_vecs_tmp = NULL;
  int capi_vecs_intent = 0;
  PyObject *vecs_capi = Py_None;
  double *mods = NULL;
  npy_intp mods_Dims[1] = {-1};
  const int mods_Rank = 1;
  PyArrayObject *capi_mods_tmp = NULL;
  int capi_mods_intent = 0;
  PyObject *mods_capi = Py_None;
  int n = 0;
  static char *capi_kwlist[] = {"vecs","mods",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:f2py_vnorm.vnorm",\
    capi_kwlist,&vecs_capi,&mods_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable mods */
  ;
  capi_mods_intent |= F2PY_INTENT_INOUT|F2PY_INTENT_C;
  capi_mods_tmp = array_from_pyobj(NPY_DOUBLE,mods_Dims,mods_Rank,capi_mods_intent,mods_capi);
  if (capi_mods_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(f2py_vnorm_error,"failed in converting 2nd argument `mods' of f2py_vnorm.vnorm to C/Fortran array" );
  } else {
    mods = (double *)(PyArray_DATA(capi_mods_tmp));

  /* Processing variable vecs */
  vecs_Dims[1]=3;
  capi_vecs_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_vecs_tmp = array_from_pyobj(NPY_DOUBLE,vecs_Dims,vecs_Rank,capi_vecs_intent,vecs_capi);
  if (capi_vecs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(f2py_vnorm_error,"failed in converting 1st argument `vecs' of f2py_vnorm.vnorm to C/Fortran array" );
  } else {
    vecs = (double *)(PyArray_DATA(capi_vecs_tmp));

  /* Processing variable n */
  n = shape(vecs,0);
  CHECKSCALAR(shape(vecs,0)==n,"shape(vecs,0)==n","hidden n","vnorm:n=%d",n) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(vecs,mods,n);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(vecs,0)==n)*/
  /* End of cleaning variable n */
  if((PyObject *)capi_vecs_tmp!=vecs_capi) {
    Py_XDECREF(capi_vecs_tmp); }
  }  /*if (capi_vecs_tmp == NULL) ... else of vecs*/
  /* End of cleaning variable vecs */
  if((PyObject *)capi_mods_tmp!=mods_capi) {
    Py_XDECREF(capi_mods_tmp); }
  }  /*if (capi_mods_tmp == NULL) ... else of mods*/
  /* End of cleaning variable mods */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of vnorm ********************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"vnorm",-1,{{-1}},0,(char *)vnorm,(f2py_init_func)f2py_rout_f2py_vnorm_vnorm,doc_f2py_rout_f2py_vnorm_vnorm},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "f2py_vnorm",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_f2py_vnorm(void) {
#else
#define RETVAL
PyMODINIT_FUNC initf2py_vnorm(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = f2py_vnorm_module = PyModule_Create(&moduledef);
#else
  m = f2py_vnorm_module = Py_InitModule("f2py_vnorm", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module f2py_vnorm (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'f2py_vnorm' is auto-generated with f2py (version:2).\nFunctions:\n"
"  vnorm(vecs,mods)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  f2py_vnorm_error = PyErr_NewException ("f2py_vnorm.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"f2py_vnorm");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
